data:
  normalization: False
HPO_metric: crps # nll mae rmse sharp crps miscal_area
HPO_radom_ratio: 1.0
calibration_type: all # all miscal rms ma isotonic
model:
  lstm:
    n_layers: 2
    hidden_size: 150 
    dropout: True
    dropout_prob: 0.1
uncertainty:
  sqr:
    scaling_factor: [12, 16, 20, 24] 
    tau: [all] # a list of two values or all it can be like this: [all, [0.025, 0.975]]
train:
  loss_function: mae   
  max_epochs: [2000]
  batch_size: 64
  early_stop: False
  early_stop.patience: 50
  early_stop.min_delta: 0
optimizer:
  type: NAdam
  base_lr: 0.001 
  eps: 1e-7  
  weight_decay: 0.01 
evaluation:
  batch_size: 64
    