data:
  normalization: False
HPO_metric: nll # nll mae rmse sharp crps
HPO_radom_ratio: 1.0
calibration_type: all # all miscal rms ma isotonic
model:
  lstm:
    n_layers: 2
    hidden_size: 150 
    dropout: True
    dropout_prob: 0.1
uncertainty:
  laplace:
    last_layer_name: linear1
    hessian_structure: [full, kron] #[full, kron, diag]
    empirical_bayes: [True]        
    epochs: [200]
    lr: [0.01]
    sigma_noise: [0.5, 1.0, 2.0] #  
    stat_noise: [False] # if True, then standard deviation, and quantiles of target attribute will affect sigma noise!
    prior_precision: [1.0, 5.0, 10.0, 20.0, 30.0]   
    temperature: [0.5, 1.0, 2.0, 4.0, 8.0]         
    n_samples: [100] 
train:
  loss_function: mae   
  max_epochs: 200
  batch_size: 64
  early_stop: True
  early_stop.patience: 50
  early_stop.min_delta: 0
optimizer:
  type: NAdam
  base_lr: 0.001 
  eps: 1e-7  
  weight_decay: 0.01 
evaluation:
  batch_size: 64
    