out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: False
  project: ENVPERMIT
dataset:
  format: PyG-EVENTEnvPermit
  name: ENVPERMITcycletimeprediction
  task: graph
  task_type: regression
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: TypeDictNode+SignNet+RWSE
  node_encoder_num_types: 26
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
posenc_SignNet:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 26
  model: DeepSet
  dim_pe: 26  # Note: In original SignNet codebase dim_pe is always equal to max_freq
  layers: 6  # Num. layers in \phi model
  post_layers: 3  # Num. layers in \rho model; The original uses the same as in \phi
  phi_hidden_dim: 64
  phi_out_dim: 64
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,26)
  model: Linear
  dim_pe: 26
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  enable_ckpt: True
  ckpt_best: True
  #ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: GINE+Transformer  # CustomGatedGCN+Performer
  layers: 5
  n_heads: 4
  dim_hidden: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.2
  attn_dropout: 0.5
  layer_norm: True
  batch_norm: False
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-2
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10