data:
  normalization: False
uncertainty:
  dropout_approximation:
    weight_regularizer: 0.000001
    dropout_regularizer: 0.00001
    num_stochastic_forward_path: [50]
HPO_metric: nll # nll mae rmse sharp crps
calibration_type: all # all miscal rms ma isotonic
model:
  lstm:
    n_layers: 2
    hidden_size: 150 
    dropout: True
    dropout_prob: 0.1
train:
  loss_function: mae   
  max_epochs: 2
  batch_size: 64
  early_stop: [True]
  early_stop.patience: 50
  early_stop.min_delta: 0
optimizer:
  type: NAdam
  base_lr: 0.001 
  eps: 1e-7  
  weight_decay: 0.0 
evaluation:
  batch_size: 64
    